### ISSUE TITLE
HTTP Post operator crash

### ISSUE THREAD

**Issue by rohitsw** [IBMStreams/streamsx.inet#109]
HTTP post operator crashes if the input stream object is null. Additional checks are required before accessing the object

Exception in thread "Thread-13" java.lang.NullPointerException
    at com.ibm.streamsx.inet.http.HTTPResponse.getInputStream(HTTPResponse.java:47)
    at com.ibm.streamsx.inet.http.HTTPResponse.getOutStreamData(HTTPResponse.java:40)
    at com.ibm.streamsx.inet.http.HTTPPostOper.process(HTTPPostOper.java:230)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1466)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:802)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:795)
    at com.ibm.streams.operator.internal.network.DeserializingStream.tuple(DeserializingStream.java:76)
    at com.ibm.streams.operator.internal.network.DeserializingStream.processRawTuple(DeserializingStream.java:65)
    at com.ibm.streams.operator.internal.runtime.api.InputPortsConduit.processRawTuple(InputPortsConduit.java:100)
    at com.ibm.streams.operator.internal.jni.JNIBridge.process(JNIBridge.java:316)

**Comment by chanskw** [comment]
Please fix in both v2.0.0 branch and master.

**Comment by ddebrunner** [comment]
This fix is missing from the 3.2.1 branch.

**Comment by chanskw** [comment]
We only back ported it for the Streams 4.0.
Should we back port fixes to all branches?  or should we do this on demand when a customer is asking for it?

**Comment by ddebrunner** [comment]
I was working with someone who hit the same issue using 3.2.1, thought it was worth noting for others. They worked around it by not having an output port.
