### ISSUE TITLE
Operator crashes with NullPointerException 

### ISSUE THREAD

**Issue by NikitaZh** [IBMStreams/streamsx.inet#252]
Hello, Team! 
WebSocketInject stops working while load test with errors:

```
Exception in thread "WebSocketWorker-27" Exception in thread "WebSocketWorker-28" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-30" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-29" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-27" Exception in thread "WebSocketWorker-29" java.lang.NullPointerExceptionjava.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-28" java.lang.NullPointerExceptionException in thread "WebSocketWorker-30" 
java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)

	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-27" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-28" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-29" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
Exception in thread "WebSocketWorker-30" java.lang.NullPointerException
	at org.java_websocket.server.WebSocketServer$WebSocketWorker$1.uncaughtException(WebSocketServer.java:638)
	at java.lang.Thread.uncaughtException(Thread.java:1289)
```
Trace:

```
07 Mar 2017 20:10:54.039 [12949] INFO spl_pe M[PEImpl.cpp:joinOperatorThreads:1474]  - Joining operator threads...
07 Mar 2017 20:10:54.039 [12949] DEBUG spl_operator M[OperatorImpl.cpp:joinOperatorThreads:237]  - Joining operator threads
07 Mar 2017 20:10:54.042 [12992] DEBUG spl_operator M[OperatorThread.cpp:run:48]  - Operator thread created
07 Mar 2017 20:10:54.419 [12996] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1714]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '295.216' -- adding connection
07 Mar 2017 20:10:54.572 [12996] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1727]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '295.216' with id '0' -- added connection
07 Mar 2017 20:10:54.630 [12997] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1714]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '234.122' -- adding connection
07 Mar 2017 20:10:54.635 [12997] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1727]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '234.122' with id '1' -- added connection
07 Mar 2017 20:10:54.635 [12998] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1714]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '228.115' -- adding connection
07 Mar 2017 20:10:54.640 [12998] DEBUG spl_pe M[PEImpl.cpp:routingInfoNotificationHandler:1727]  - Stream from output port index 0 has a new consumer whose TCP endpoint is '228.115' with id '2' -- added connection
07 Mar 2017 20:10:58.875 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44277 err: Connection reset by peer
07 Mar 2017 20:11:03.594 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44279 err: Connection reset by peer
07 Mar 2017 20:11:08.711 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44281 err: Connection reset by peer
07 Mar 2017 20:11:13.836 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44284 err: Connection reset by peer
07 Mar 2017 20:11:18.923 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44287 err: Connection reset by peer
07 Mar 2017 20:11:24.034 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44290 err: Connection reset by peer
07 Mar 2017 20:11:28.161 [12991] ERROR #splapptrc,J[292],P[296],WebSocketInject_3 M[WSServer.java:com.ibm.streamsx.inet.wsserver.WSServer.onError:107]  - WSServer onError(): client: 192.168.255.211/192.168.255.211:44292 err: Connection reset by peer
```
any solution?

**Comment by joergboe** [comment]
Which version of the toolkit do you use and in which environment?

**Comment by NikitaZh** [comment]
com.ibm.streamsx.inet[2.7.4]
streams - 4.2.0.3

**Comment by joergboe** [comment]
How often does this happen immediately, after some time under special circumstances?
This exception is during Java-WebSocket instantiation. No idea why this happens.

**Comment by NikitaZh** [comment]
We assume it happens due to heavy load issues, socket crashes not immediately, but after some time. Certain circumstances weren't caught. We haven't even managed to crash socket manually, any idea how to trace it?

**Comment by siegenth** [comment]
I believe you'll need to pull down the Java-WebSocket code and add your own traces to work out what is wrong.  Check the opt/websocket/CREDIT for a link to the GIT hub project  that provided Java-WebSocket jar.

**Comment by joergboe** [comment]
This is now tracked here:
https://github.com/IBMStreams/streamsx.inetserver/issues/15
